### ISSUE TITLE
`bower install && gulp install` error

### ISSUE THREAD

**Issue by yasulab** [coderdojo-tokyo/web#1]
coderdojo-japanのリニューアルに向けてこちらを fork して build しようと考えているのですが、
coderdojo-tokyo package 周りで早速エラーが起こってしまいましたorz

もし何か心当たりがあれば、アドバイスを頂けると嬉しいですorz orz
## Error 箇所

```
> coderdojo-tokyo@2.0.0 postinstall /Users/yasulab/web
> bower install && gulp install

[15:58:56] Requiring external module coffee-script/register
[15:58:58] Using gulpfile ~/web/gulpfile.coffee
[15:58:58] Starting 'install'...
[15:58:58] Starting 'clean'...
[15:58:58] Finished 'install' after 4.07 ms
[15:58:58] Finished 'clean' after 4.43 ms
[15:58:58] Starting 'bower'...
[15:58:58] Starting 'bower-update'...
[15:58:58] Finished 'bower' after 1.13 ms
[15:58:58] Starting 'icon'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn sketchtool ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1038:32)
  at child_process.js:1129:20
  at process._tickCallback (node.js:372:11)
```
## npm-debug.log

```
155 info install coderdojo-tokyo@2.0.0
156 info postinstall coderdojo-tokyo@2.0.0
157 verbose unsafe-perm in lifecycle true
158 info coderdojo-tokyo@2.0.0 Failed to exec postinstall script
159 verbose stack Error: Exit status 1
159 verbose stack     at EventEmitter.<anonymous> (/Users/yasulab/.nodebrew/node/v0.11.14/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
159 verbose stack     at EventEmitter.emit (events.js:110:17)
159 verbose stack     at ChildProcess.<anonymous> (/Users/yasulab/.nodebrew/node/v0.11.14/lib/node_modules/npm/lib/utils/spawn.js:24:14)
159 verbose stack     at ChildProcess.emit (events.js:110:17)
159 verbose stack     at maybeClose (child_process.js:1000:16)
159 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1072:5)
160 verbose pkgid coderdojo-tokyo@2.0.0
161 verbose cwd /Users/yasulab/web
162 error Darwin 14.4.0
163 error argv "node" "/Users/yasulab/.nodebrew/current/bin/npm" "install"
164 error node v0.11.14
165 error npm  v2.13.1
166 error code ELIFECYCLE
167 error coderdojo-tokyo@2.0.0 postinstall: `bower install && gulp install`
167 error Exit status 1
168 error Failed at the coderdojo-tokyo@2.0.0 postinstall script 'bower install && gulp install'.
168 error This is most likely a problem with the coderdojo-tokyo package,
168 error not with npm itself.
168 error Tell the author that this fails on your system:
168 error     bower install && gulp install
168 error You can get their info via:
168 error     npm owner ls coderdojo-tokyo
168 error There is likely additional logging output above.
169 verbose exit [ 1, true ]
```

cf. [full error - gist](https://gist.github.com/yasulab/c7810721a0e678f0078c)

**Comment by cognitom** [comment]
iconのところで落ちているので、[ここ](https://github.com/cognitom/gulp-sketch)のInstall手順のところを参考に、SketchToolを入れてもらうと解決するような気がします。

ここは、オプショナルなタスクにしておくべきだったかも... (汗)

**Comment by yasulab** [comment]
ありがとうございます! 試してみます :smile_cat:

**Comment by yasulab** [comment]
無事に Icon 生成できました!
...が、今度は `image` の部分で落ちてしまいましたorz

```
[16:07:54] Finished 'icon' after 1.34 s
[16:07:54] Starting 'parse'...
[16:07:54] Starting 'html'...
[16:07:54] Starting 'coffee'...
[16:07:54] Starting 'css'...
[16:07:54] Starting 'image'...
Trace: { [Error: ENOENT, open '/Users/yasulab/web/public/font/coderdojo.css']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/yasulab/web/public/font/coderdojo.css' }
  at onResolvePath (/Users/yasulab/web/node_modules/gulp-cssimport/gulp-cssimport.js:85:13)
  at /Users/yasulab/web/node_modules/gulp-cssimport/helper.js:94:3
  at fs.js:224:20
  at OpenReq.Req.done (/Users/yasulab/web/node_modules/bower/node_modules/bower-json/node_modules/graceful-fs/graceful-fs.js:143:5)
  at OpenReq.done (/Users/yasulab/web/node_modules/bower/node_modules/bower-json/node_modules/graceful-fs/graceful-fs.js:63:22)
  at OpenReq.Req.done (/Users/yasulab/web/node_modules/bower/node_modules/bower-registry-client/node_modules/graceful-fs/graceful-fs.js:143:5)
  at OpenReq.done (/Users/yasulab/web/node_modules/bower/node_modules/bower-registry-client/node_modules/graceful-fs/graceful-fs.js:63:22)
  at OpenReq.Req.done (/Users/yasulab/web/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:143:5)
  at OpenReq.done (/Users/yasulab/web/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:63:22)
  at Object.oncomplete (fs.js:93:15)

/Users/yasulab/web/node_modules/gulp-cssimport/gulp-cssimport.js:86
                throw err;
                      ^
Error: ENOENT, open '/Users/yasulab/web/public/font/coderdojo.css'
  at Error (native)
```

**Comment by yasulab** [comment]
とりあえず CSS の部分だけをコンパイル対象から外して、デプロイ & Web Hosting までやってみました :)

http://coderdojo-japan.parseapp.com/

@cognitom 今夜の呑み会とかで上記の件について情報を教えてもらえると嬉しいです :sob:

**Comment by cognitom** [comment]
あうち! 了解です :ok_hand:

**Comment by cognitom** [comment]
これだ!
https://github.com/cognitom/symbols-for-sketch/issues/11

**Comment by cognitom** [comment]
直しました〜
https://github.com/coderdojo-tokyo/web/commit/9142c160f804e74f23dea3724b0c075619dcaf3f

**Comment by yasulab** [comment]
`npm install` や `gulp watch`、`parse deploy`も無事に通りました!

http://coderdojo-japan.parseapp.com/

ありがとうございます! :smile_cat:  :star2:
